# Generated by Django 2.2.28 on 2023-06-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_lee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lee',
        ),
    ]
