# Generated by Django 2.2.28 on 2023-06-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_lee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hey',
        ),
    ]
